name: commzy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider_plus: ^7.1.0
  flutter:
    sdk: flutter
  get: ^4.7.2
  http: ^1.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  rename_app: ^1.6.3
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
